# Dependabot will run on day 3 of each month at 03:21 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "21 3 3 * *"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/src-admin"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "21 3 3 * *"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "21 3 3 * *"
    open-pull-requests-limit: 15
